services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: